server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: tool-unique-service
          uri: lb://tool-unique-service
          predicates:
            - Path=/api/tool-unique/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: tool-group-service
          uri: lb://tool-group-service
          predicates:
            - Path=/api/tool-group/**,/api/category/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loan/**,/api/payment/**
          filters:
            - RemoveRequestHeader=Cookie
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    discovery:
      enabled: true
    config:
      uri: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.cloud.gateway.route: WARN
    com.netflix.discovery: WARN
    org.springframework.cloud.netflix.eureka: WARN
