server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tool-rent-db-loan-and-payment}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
    show-sql: ${SHOW_SQL:false}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:9090/realms/ToolRent}
          jwk-set-uri: ${KEYCLOAK_JWK:http://localhost:9090/realms/ToolRent/protocol/openid-connect/certs}
